### ISSUE TITLE
Do we want sdl::Window to provide easy access to SDL_GL_* and SDL_Vulkan_* functions?

### ISSUE THREAD

**Issue by Ybalrid** [Edhebi/cpp-sdl2#12]
These are generally just functions that take the window pointer and a few other things. It would be nice to provide a consistent interface. (Ignoring the ones that have to do the loading of libraries).

Basically, the functions needed to create a valid OpenGL context, and the functions required to create a valid VulkanSurfaceKHR object.

In the case of Vulkan, they are exposed in SDL2\SDL_Vulkan.h, and I think this file will fail to compile if you don't have vulkan.h from the SDK accessible. So this would definitively need to be toggleable with a define or something like that.

Here's the list of relevant functions for OpenGL:

 - `SDL_GL_SetAttribute()`
 - `SDL_GL_CreateContext()`/`SDL_GL_DeleteContext()`
 - `SDL_GL_SwapWindow()`

Here's the list of relevant functions for Vulkan:

 - `SDL_Vulkan_GetInstanceExtensions();`
 - `SDL_Vulkan_CreateSurface();`

**Comment by Edhebi** [comment]
Definetly nice to have them around. Maybe in `sdl::gl` and `sdl::vk` namespaces ?
