### ISSUE TITLE
Fix warnings on non Microsoft compilers

### ISSUE THREAD

**Issue by Edhebi** [Edhebi/cpp-sdl2#4]
This code was only tested for VS17 (/W4), and other compilers still raise some warnings

Edit : add list of compilers to check:

- [x] GCC on Linux
- [x] MinGW on Windows
- [x] clang on Linux/Mac
- [x] emscripten (LLVM based, probably the same as clang) -> WASM
- [x] devkitpro toolchains (OpenSource SDK for PSP, Switch, and many, many things)

Ideally, any "open" platform where a modern C++ compiler is usable should be listed above.

**Comment by Ybalrid** [comment]
Renaming issue as "Fix warnings on non-msvc compilers". Editing first post to add todo checklist.

**Comment by Ybalrid** [comment]
In the general case, cpp-sdl2 compiles pretty cleanly now, so I'm closing this as a non-issue. 

It would be neat to cover all these platform in some way in CI, as they have various idiosyncrasies that this library should probably end from the end user.

cpp-sdl2 is usable on a lot of things passed the few hiccups of last year. Throwing it at a nintendo switch (albeit, the unofficial - but legal - homebrew SDK) and at a web browser was a good idea, it made some of the code a tiny bit more robust. :wink:
