### ISSUE TITLE
Wrap more SDL2 functionalities

### ISSUE THREAD

**Issue by Edhebi** [Edhebi/cpp-sdl2#6]
Some methods are still not wrapped on existing Objects
Some categories are not wrapped yet and could be
~OpenGL helpers from SDL are still not wrapped~ **done** ✔️ 

- [x] Joystick
- [x] Timer
- [x] Haptic
- [x] Controller
- [x] MessageBox
- [x] Platform
- [x] Clipboard
- [x] Power Info
- [x] Dynamic libraries

Things that aren't needed to be wrapped because they have standard equivalent as part of the C++ language or library:

- Filesystem access (aka "RWops")
- Threads
- Synchronization objects (e.g. mutexes)
- Atomics

**Comment by Ybalrid** [comment]
I suggest shared object loading. I do like opening my DLLs you know... ^^"

**Comment by Ybalrid** [comment]
Will need to establish the list of SDL APIs that may benefit from an useful C++ wrapper

**Comment by Ybalrid** [comment]
commit 7e0f98fde03c6c5f791bd861c15bcfc0a18a31e6 tick the power, platform and clipbooard items in 1st post

**Comment by Ybalrid** [comment]
I'll work on adding timers to the wrapper today.

**Comment by Ybalrid** [comment]
Well, I haven't got around adding the SDL timers and totally forgot about them, however, the joystick and gamepad APIs needs by themselves some initialization too. I am currently wrapping the GameController api because I need it for some projects.

**Comment by Ybalrid** [comment]
Haptics merged in as of commit 7b681a1e984cacbb12a8a7d0c1165a7783362995

**Comment by Ybalrid** [comment]
everything listed in the fist post is done
